<script type="text/javascript" src="/js/new_plugins/parsley/parsley.min.js?1591796224"></script>
<script type="text/javascript" src="/js/new_plugins/numeral/numeral.min.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/datatables.min.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/buttons-1.5.1/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/buttons-1.5.1/buttons.jqueryui.min.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/buttons-1.5.1/buttons.html5.min.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/buttons-1.5.1/buttons.print.min.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/jszip-2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/pdfmake-0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/pdfmake-0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="/js/new_plugins/datatables/sorting/datetime-moment.js"></script>
<script type="text/javascript" src="/js/new_plugins/uri/uri.js"></script>
<script type="text/javascript" src="/js/brokerlive/brokerlive.systemTasks.js"></script>